### ISSUE TITLE
SilverStripe 4 upgrade tasks

### ISSUE THREAD

**Issue by nspyke** [symbiote/silverstripe-notifications#18]
I have a project that makes heavy use of this module.

Is there any known breaking changes that would need to be fixed in this module to make it compatible? 

I'm happy to do the upgrade and make a pull request, but I'd like to know what I'm getting into.

**Comment by nyeholt** [comment]
Hi Nik - not sure off the top of my head. We've got a project coming up "soonish" that may require us updating this, so if that happens I'll be reviewing the effort then.

**Comment by nglasl** [comment]
Closing this one now that the PR has been merged. Thanks for your work here :)
